# Generated by Django 3.0.6 on 2020-08-04 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200805_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='like',
        ),
        migrations.AddField(
            model_name='quiz',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
