# Generated by Django 3.0.6 on 2020-08-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=150, verbose_name='ニックネーム'),
        ),
    ]
