# Generated by Django 3.0.6 on 2020-05-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='publish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
