# Generated by Django 3.0.6 on 2020-08-06 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200805_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='liked_article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='liked_quiz', to=settings.AUTH_USER_MODEL),
        ),
    ]
