# Generated by Django 3.0.6 on 2020-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='choice_long',
            field=models.BooleanField(default=False),
        ),
    ]
