# Generated by Django 3.0.6 on 2020-05-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_choice_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(max_length=200),
        ),
    ]
