# Generated by Django 3.0.6 on 2020-05-27 06:33

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200527_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='description'),
        ),
    ]
