# Generated by Django 3.0.6 on 2020-08-06 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_correction_login_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correction',
            name='login_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_corrections', to=settings.AUTH_USER_MODEL),
        ),
    ]
