# Generated by Django 3.0.6 on 2020-08-06 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200806_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answered_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
