# Generated by Django 3.0.6 on 2020-05-29 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200527_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='choice1',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='choice2',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='choice3',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='choice4',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='publish',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='DescriptionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=100)),
                ('yomi', models.CharField(blank=True, max_length=100)),
                ('definition', models.CharField(blank=True, max_length=100)),
                ('usage', models.CharField(blank=True, max_length=100)),
                ('example_ja', models.TextField(blank=True, max_length=100)),
                ('example_en', models.TextField(blank=True, max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Quiz')),
            ],
        ),
    ]
