# Generated by Django 3.0.6 on 2020-08-06 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20200806_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='choice1_count',
        ),
        migrations.AddField(
            model_name='quiz',
            name='choice1_count',
            field=models.ManyToManyField(blank=True, null=True, related_name='choice1_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='choice2_count',
        ),
        migrations.AddField(
            model_name='quiz',
            name='choice2_count',
            field=models.ManyToManyField(blank=True, null=True, related_name='choice2_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='choice3_count',
        ),
        migrations.AddField(
            model_name='quiz',
            name='choice3_count',
            field=models.ManyToManyField(blank=True, null=True, related_name='choice3_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='choice4_count',
        ),
        migrations.AddField(
            model_name='quiz',
            name='choice4_count',
            field=models.ManyToManyField(blank=True, null=True, related_name='choice4_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
