# Generated by Django 3.0.6 on 2020-05-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20200529_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ChoicesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_explanation_1', models.CharField(blank=True, max_length=100)),
                ('choice_explanation_2', models.CharField(blank=True, max_length=100)),
                ('choice_explanation_3', models.CharField(blank=True, max_length=100)),
                ('choice_explanation_4', models.CharField(blank=True, max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Quiz')),
            ],
        ),
    ]
