# Generated by Django 3.0.6 on 2020-08-06 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20200806_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='first_try_correct',
            field=models.ManyToManyField(blank=True, null=True, related_name='question_first_try_correct', to=settings.AUTH_USER_MODEL),
        ),
    ]
