# Generated by Django 3.0.6 on 2020-05-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20200529_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptiondetail',
            name='example_yomi',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
