# Generated by Django 3.0.6 on 2020-05-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_descriptiondetail_example_yomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_en',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_yomi',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
