# Generated by Django 3.0.6 on 2020-05-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20200530_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicesdetail',
            name='choice_explanation_1',
            field=models.CharField(blank=True, help_text='hello', max_length=100),
        ),
    ]
