# Generated by Django 3.0.6 on 2020-08-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20200807_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptiondetail',
            name='word_in_sentence',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
