# Generated by Django 3.0.6 on 2020-05-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20200531_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='choice1_detail',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='choice2_detail',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='choice3_detail',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='choice4_detail',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='choicesdetail',
            name='choice_explanation_1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
