# Generated by Django 3.0.6 on 2020-05-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20200531_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicesdetail',
            name='choice_explanation_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='choicesdetail',
            name='choice_explanation_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='choicesdetail',
            name='choice_explanation_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='choicesdetail',
            name='choice_explanation_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='descriptiondetail',
            name='definition',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='descriptiondetail',
            name='example_en',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='descriptiondetail',
            name='example_ja',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='descriptiondetail',
            name='example_yomi',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='descriptiondetail',
            name='usage',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='descriptiondetail',
            name='word',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='descriptiondetail',
            name='yomi',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
