# Generated by Django 3.0.6 on 2020-08-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_descriptiondetail_word_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_reading',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
