# Generated by Django 3.0.6 on 2020-06-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20200531_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
