# Generated by Django 3.0.6 on 2020-06-04 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20200602_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('title', models.TextField(max_length=300, null=True)),
                ('public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['chapter'],
            },
        ),
        migrations.CreateModel(
            name='LessonVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=300)),
                ('yomi', models.CharField(blank=True, max_length=300)),
                ('definition', models.CharField(blank=True, max_length=300)),
                ('usage', models.CharField(blank=True, max_length=300)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=300, null=True)),
                ('answer', models.TextField(max_length=300, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonKanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=300, null=True)),
                ('definition', models.CharField(max_length=300, null=True)),
                ('yomi', models.CharField(max_length=300, null=True)),
                ('example', models.TextField(max_length=300, null=True)),
                ('example_en', models.TextField(max_length=300, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonGrammar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar', models.CharField(max_length=300, null=True)),
                ('desc', models.TextField(max_length=300, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=300, null=True)),
                ('sentence', models.TextField(max_length=300, null=True)),
                ('sentence_yomi', models.TextField(max_length=300, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Lesson')),
            ],
        ),
    ]
