# Generated by Django 3.1 on 2020-09-01 11:38

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20200901_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='explanation',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nickname'),
        ),
    ]
