# Generated by Django 3.0.6 on 2020-06-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_lesson_lessonbody_lessongrammar_lessonkanji_lessonquestion_lessonvocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbody',
            name='sentence_en',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
