# Generated by Django 3.1 on 2020-09-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20200901_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=150, null=True, verbose_name='Nickname'),
        ),
    ]
