# Generated by Django 3.0.6 on 2020-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_lessonbody_sentence_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquestion',
            name='question_en',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
