# Generated by Django 3.0.6 on 2020-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_lessonquestion_question_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessongrammar',
            name='desc',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
