# Generated by Django 3.1 on 2021-01-23 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20200901_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
