# Generated by Django 3.1 on 2021-01-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20210123_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Articles',
            old_name='category',
            new_name='category'
        )
    ]
