# Generated by Django 3.1 on 2021-01-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20210123_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Articles',
            old_name='related_basics',
            new_name='related_articles'
        )
    ]
