# Generated by Django 3.0.6 on 2020-06-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20200604_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquestion',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
