# Generated by Django 3.0.6 on 2020-06-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_lessonquestion_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquestion',
            name='answer_yomi',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='question_yomi',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
