# Generated by Django 3.1 on 2021-01-30 01:29

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_auto_20210123_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, null=True)),
                ('category_slug', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, null=True)),
                ('tag_slug', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogJapanese2Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_in_sentence', models.CharField(blank=True, max_length=200, null=True)),
                ('word_form', models.CharField(blank=True, max_length=200, null=True)),
                ('word', models.CharField(blank=True, max_length=200)),
                ('yomi', markdownx.models.MarkdownxField(blank=True, max_length=200)),
                ('definition', markdownx.models.MarkdownxField(blank=True, max_length=200)),
                ('usage', markdownx.models.MarkdownxField(blank=True, max_length=200)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_2_detail', to='quiz.blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogJapanese2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField(null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_2', to='quiz.blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogJapanese1Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_in_sentence', models.CharField(blank=True, max_length=200, null=True)),
                ('word_form', models.CharField(blank=True, max_length=200, null=True)),
                ('word', models.CharField(blank=True, max_length=200)),
                ('yomi', markdownx.models.MarkdownxField(blank=True, max_length=200)),
                ('definition', markdownx.models.MarkdownxField(blank=True, max_length=200)),
                ('usage', markdownx.models.MarkdownxField(blank=True, max_length=200)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_1_detail', to='quiz.blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogJapanese1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField(null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_1', to='quiz.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_blogs', to='quiz.blogcategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='tag_blogs', to='quiz.BlogTag'),
        ),
    ]
