# Generated by Django 3.0.6 on 2020-06-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_auto_20200605_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonkanji',
            name='example_yomi',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
