# Generated by Django 3.1 on 2021-01-30 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_auto_20210130_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogjapanese1detail',
            name='word_form',
        ),
        migrations.RemoveField(
            model_name='blogjapanese1detail',
            name='word_in_sentence',
        ),
        migrations.RemoveField(
            model_name='blogjapanese2detail',
            name='word_form',
        ),
        migrations.RemoveField(
            model_name='blogjapanese2detail',
            name='word_in_sentence',
        ),
    ]
