# Generated by Django 3.1 on 2021-01-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20210130_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_reading',
            field=models.FileField(blank=True, null=True, upload_to='quiz/reading'),
        ),
    ]
