# Generated by Django 3.0.6 on 2020-06-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20200610_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonbody',
            name='reading',
        ),
        migrations.AddField(
            model_name='lesson',
            name='reading',
            field=models.BooleanField(default=False),
        ),
    ]
