# Generated by Django 3.0.6 on 2020-06-11 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20200610_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='vocab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonbody',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Lesson'),
        ),
        migrations.AlterField(
            model_name='lessongrammar',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Lesson'),
        ),
        migrations.AlterField(
            model_name='lessonkanji',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Lesson'),
        ),
        migrations.AlterField(
            model_name='lessonquestion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Lesson'),
        ),
        migrations.AlterField(
            model_name='lessonvocabulary',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Lesson'),
        ),
    ]
