# Generated by Django 3.0.6 on 2020-06-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20200612_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonbody',
            options={'ordering': ['lesson', 'id']},
        ),
        migrations.AlterModelOptions(
            name='lessongrammar',
            options={'ordering': ['lesson', 'id']},
        ),
        migrations.AlterModelOptions(
            name='lessonkanji',
            options={'ordering': ['lesson', 'id']},
        ),
        migrations.AlterModelOptions(
            name='lessonquestion',
            options={'ordering': ['lesson', 'id']},
        ),
        migrations.AlterModelOptions(
            name='lessonvocabulary',
            options={'ordering': ['lesson', 'id']},
        ),
    ]
