# Generated by Django 3.0.6 on 2020-06-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_auto_20200612_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='exercise',
            field=models.BooleanField(default=False),
        ),
    ]
