# Generated by Django 3.0.6 on 2020-06-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_lesson_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbody',
            name='sentence_casual',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lessongrammar',
            name='casual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonvocabulary',
            name='cacual',
            field=models.BooleanField(default=False),
        ),
    ]
