# Generated by Django 3.0.6 on 2020-06-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_auto_20200615_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonvocabulary',
            old_name='cacual',
            new_name='casual',
        ),
    ]
