# Generated by Django 3.0.6 on 2020-06-20 06:21

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_auto_20200620_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforeyoustart',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
