# Generated by Django 3.0.6 on 2020-06-20 06:43

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_auto_20200620_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basics',
            name='content',
            field=markdownx.models.MarkdownxField(null=True),
        ),
    ]
