# Generated by Django 3.0.6 on 2020-06-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0040_auto_20200620_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='basics',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='basics_image/'),
        ),
    ]
