# Generated by Django 3.0.6 on 2020-06-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_basics_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_image', models.ImageField(blank=True, null=True, upload_to='basics_image/')),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Basics')),
            ],
        ),
    ]
