# Generated by Django 3.0.6 on 2020-06-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0042_basicimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonGrammarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_gramamr_image', models.ImageField(blank=True, null=True, upload_to='grammar_image/')),
                ('lesson_grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.LessonGrammar')),
            ],
        ),
        migrations.CreateModel(
            name='BeforeYouStartImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='before_image/')),
                ('before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.BeforeYouStart')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='article_image/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Articles')),
            ],
        ),
    ]
