# Generated by Django 3.0.6 on 2020-06-25 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0044_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(5, 'It should be less than 500 characters! Suimasen!')]),
        ),
        migrations.AlterField(
            model_name='correction',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='correction',
            name='text',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(5, 'It should be less than 500 characters! Suimasen!')]),
        ),
    ]
