# Generated by Django 3.0.6 on 2020-06-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0045_auto_20200625_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'casual'), (2, 'formal'), (3, 'super formal')], null=True),
        ),
    ]
