# Generated by Django 3.0.6 on 2020-06-25 05:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0047_auto_20200625_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='correction',
            name='title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='correction',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='correction',
            name='text',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(5, 'Text should be less than 500 characters! Suimasen!'), django.core.validators.MinLengthValidator(1, 'Text is empty')]),
        ),
        migrations.CreateModel(
            name='CorrectionSentences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(blank=True, max_length=50000, null=True)),
                ('corrected', models.CharField(blank=True, max_length=50000, null=True)),
                ('desc', models.CharField(blank=True, max_length=50000, null=True)),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Correction')),
            ],
        ),
    ]
