# Generated by Django 3.0.6 on 2020-06-25 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0048_auto_20200625_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='text',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500, 'Text should be less than 500 characters! Suimasen!'), django.core.validators.MinLengthValidator(1, 'Text is empty')]),
        ),
        migrations.AlterField(
            model_name='correction',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Casual'), (2, 'Formal'), (3, 'SUPER Formal')], null=True),
        ),
        migrations.AlterField(
            model_name='correctionsentences',
            name='corrected',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='correctionsentences',
            name='desc',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='correctionsentences',
            name='original',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
