# Generated by Django 3.0.6 on 2020-06-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0049_auto_20200625_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correction',
            options={'ordering': ['updated']},
        ),
        migrations.AddField(
            model_name='correction',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='correction',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'SUPER Casual'), (2, 'Casual'), (3, 'Formal'), (4, 'SUPER Formal')], null=True),
        ),
    ]
