# Generated by Django 3.0.6 on 2020-06-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0050_auto_20200626_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correction',
            options={'ordering': ['-updated']},
        ),
    ]
