# Generated by Django 3.0.6 on 2020-06-26 00:01

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0051_auto_20200626_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionsentences',
            name='corrected',
            field=markdownx.models.MarkdownxField(blank=True, max_length=50000, null=True),
        ),
    ]
