# Generated by Django 3.0.6 on 2020-06-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0052_auto_20200626_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionsentences',
            name='corrected',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
