# Generated by Django 3.0.6 on 2020-06-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0053_auto_20200626_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptiondetail',
            name='definition',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='descriptiondetail',
            name='usage',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
