# Generated by Django 3.0.6 on 2020-06-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0054_auto_20200626_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='title',
            field=models.TextField(blank=True, default='New!', max_length=100, null=True),
        ),
    ]
