# Generated by Django 3.0.6 on 2020-06-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0055_auto_20200626_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correction',
            options={'ordering': ['public', '-updated']},
        ),
        migrations.AddField(
            model_name='correctionsentences',
            name='correted_yomi',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
