# Generated by Django 3.0.6 on 2020-06-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0056_auto_20200626_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctionsentences',
            old_name='correted_yomi',
            new_name='corrected_yomi',
        ),
    ]
