# Generated by Django 3.0.6 on 2020-06-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0057_auto_20200626_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonvocabulary',
            options={'ordering': ['lesson', 'order']},
        ),
        migrations.AddField(
            model_name='lessonvocabulary',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
