# Generated by Django 3.0.6 on 2020-06-27 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0058_auto_20200627_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='basics',
            name='related_articles',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.Articles'),
        ),
        migrations.AddField(
            model_name='basics',
            name='related_basics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Basics'),
        ),
    ]
