# Generated by Django 3.0.6 on 2020-06-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0059_auto_20200627_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='related_basics',
            field=models.ManyToManyField(blank=True, null=True, related_name='_articles_related_basics_+', to='quiz.Articles'),
        ),
        migrations.RemoveField(
            model_name='basics',
            name='related_basics',
        ),
        migrations.AddField(
            model_name='basics',
            name='related_basics',
            field=models.ManyToManyField(blank=True, null=True, related_name='_basics_related_basics_+', to='quiz.Basics'),
        ),
    ]
