# Generated by Django 3.0.6 on 2020-07-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0060_auto_20200627_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlesCategory',
            new_name='ArticlesTag',
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['update']},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='category',
        ),
        migrations.AddField(
            model_name='articles',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.ArticlesTag'),
        ),
        migrations.AddField(
            model_name='articles',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
