# Generated by Django 3.0.6 on 2020-07-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0061_auto_20200701_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-update']},
        ),
        migrations.AddField(
            model_name='articles',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
