# Generated by Django 3.0.6 on 2020-07-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0062_auto_20200701_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='title_slug',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basics',
            name='title_slug',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_slug',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='summary',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
