# Generated by Django 3.0.6 on 2020-07-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0063_auto_20200702_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='title_slug',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basics',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
