# Generated by Django 3.0.6 on 2020-07-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0064_auto_20200702_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title_slug',
            field=models.TextField(blank=True, default='chapter<django.db.models.fields.IntegerField>:<django.db.models.fields.IntegerField>', max_length=255, null=True),
        ),
    ]
