# Generated by Django 3.0.6 on 2020-07-02 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0065_auto_20200702_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='title_slug',
        ),
    ]
