# Generated by Django 3.0.6 on 2020-07-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0066_remove_lesson_title_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title_slug',
            field=models.TextField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='basics',
            name='title_slug',
            field=models.TextField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='correction',
            name='title_slug',
            field=models.TextField(max_length=100, null=True, unique=True),
        ),
    ]
