# Generated by Django 3.0.6 on 2020-07-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0070_auto_20200704_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='category',
        ),
    ]
