# Generated by Django 3.0.6 on 2020-07-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0071_remove_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Nihongo'), (2, 'Nihon')], null=True),
        ),
    ]
