# Generated by Django 3.0.6 on 2020-07-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0072_articles_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='category',
        ),
    ]
