# Generated by Django 3.0.6 on 2020-07-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0073_remove_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='thumbnail_attr',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
