# Generated by Django 3.0.6 on 2020-07-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0074_articles_thumbnail_attr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-create']},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='thumbnail_attr',
        ),
        migrations.AddField(
            model_name='articles',
            name='create',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
