# Generated by Django 3.0.6 on 2020-07-12 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0075_auto_20200712_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-create', '-update']},
        ),
        migrations.AlterField(
            model_name='articles',
            name='create',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
