# Generated by Django 3.0.6 on 2020-07-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0076_auto_20200712_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-update']},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='create',
        ),
    ]
