# Generated by Django 3.0.6 on 2020-07-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0080_auto_20200713_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='aki',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='aki',
            field=models.BooleanField(default=False),
        ),
    ]
