# Generated by Django 3.0.6 on 2020-07-14 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0081_auto_20200714_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ArticleReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=500, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Articles')),
            ],
        ),
    ]
